// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_sys = require("bs-platform/lib/js/caml_sys.js");

var homedir = Caml_sys.caml_sys_getenv("HOME");

var savepath = homedir + "/.uba.json";

exports.homedir = homedir;
exports.savepath = savepath;
/* homedir Not a pure module */
