// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Uba$Octoberdelight = require("./Uba.bs.js");
var Config$Octoberdelight = require("./Config.bs.js");

var uba = Uba$Octoberdelight.genesis(/* () */0);

console.log(uba);

Uba$Octoberdelight.store(uba, Config$Octoberdelight.savepath);

var uba2 = Uba$Octoberdelight.load(Config$Octoberdelight.savepath);

console.log(uba2);

console.log(Config$Octoberdelight.lsout);

console.log(uba2.freeagents.map((function (fa) {
            return Js_primitive.undefined_to_opt(fa.skill["P"]);
          })));

exports.uba = uba;
exports.uba2 = uba2;
/* uba Not a pure module */
