// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Uba$Octoberdelight = require("./Uba.bs.js");

var uba = Uba$Octoberdelight.genesis(/* () */0);

var fa = uba.freeagents;

console.log(Caml_array.caml_array_get(fa, 0));

var faname = Caml_array.caml_array_get(fa, 0).name;

console.log(faname);

exports.uba = uba;
exports.fa = fa;
exports.faname = faname;
/* uba Not a pure module */
