// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Random = require("bs-platform/lib/js/random.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

Random.self_init(/* () */0);

var dictfile = "/usr/share/dict/words";

var wordpool = $$String.trim(Fs.readFileSync(dictfile, "utf8")).split("\n").filter((function (w) {
          return w.length <= 6;
        })).map((function (w) {
        return w.toUpperCase();
      }));

var wordpoolLen = wordpool.length;

function draw() {
  var x1 = Random.$$int(wordpoolLen);
  var x2 = Random.$$int(wordpoolLen);
  return Caml_array.caml_array_get(wordpool, x1) + Caml_array.caml_array_get(wordpool, x2);
}

var maxWordSize = 6;

exports.dictfile = dictfile;
exports.maxWordSize = maxWordSize;
exports.wordpool = wordpool;
exports.wordpoolLen = wordpoolLen;
exports.draw = draw;
/*  Not a pure module */
