// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Namepool$Octoberdelight = require("./Namepool.bs.js");

var athleteName = Namepool$Octoberdelight.draw(/* () */0);

console.log(athleteName);

exports.athleteName = athleteName;
/* athleteName Not a pure module */
